# Generated by Django 3.0.4 on 2020-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(default='address0'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='description0'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='description0'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
    ]
